services:
  
  demo.busybee:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "127.0.0.1:8100:8080"
    depends_on:
      - seq.busybee
    environment:
      OtlpExporterOptions__logging__Endpoint: http://seq.busybee/ingest/otlp/v1/logs
      OtlpExporterOptions__logging__Protocol: HttpProtobuf
      OtlpExporterOptions__tracing__Endpoint: http://seq.busybee/ingest/otlp/v1/traces
      OtlpExporterOptions__tracing__Protocol: HttpProtobuf
    networks:
      - busybee.internal
  
  seq.busybee:
    image: datalust/seq:2025.2
    ports:
      - "127.0.0.1:8200:80"
    environment:
      ACCEPT_EULA: Y
      SEQ_FIRSTRUN_NOAUTHENTICATION: true
    networks:
      - busybee.internal
        
  prometheus.busybee:
    image: prom/prometheus:v3.5.0
    depends_on:
      - demo.busybee
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
    networks:
      - busybee.internal
    ports:
      - "127.0.0.1:8300:9090"


networks:
  busybee.internal:
    driver: bridge